/**
 * Event status types
 */
export const EventStatus = {
  PENDING_FACULTY_APPROVAL: 'PENDING_FACULTY_APPROVAL',
  PENDING_DEAN_APPROVAL: 'PENDING_DEAN_APPROVAL',
  NEEDS_REVISION_DEAN: 'NEEDS_REVISION_DEAN',
  PENDING_DEANSHIP_APPROVAL: 'PENDING_DEANSHIP_APPROVAL',
  NEEDS_REVISION_DEANSHIP: 'NEEDS_REVISION_DEANSHIP',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

/**
 * Approval status types
 */
export const ApprovalStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

/**
 * User role types
 */
export const UserRole = {
  STUDENT: 'STUDENT',
  CLUB_LEADER: 'CLUB_LEADER',
  FACULTY_LEADER: 'FACULTY_LEADER',
  DEAN_OF_FACULTY: 'DEAN_OF_FACULTY',
  DEANSHIP_OF_STUDENT_AFFAIRS: 'DEANSHIP_OF_STUDENT_AFFAIRS',
  ADMIN: 'ADMIN'
};

/**
 * Notification types
 */
export const NotificationType = {
  EVENT_PENDING_APPROVAL: 'EVENT_PENDING_APPROVAL',
  EVENT_APPROVED: 'EVENT_APPROVED',
  EVENT_REJECTED: 'EVENT_REJECTED',
  EVENT_NEEDS_REVISION: 'EVENT_NEEDS_REVISION',
  EVENT_REMINDER_1_DAY: 'EVENT_REMINDER_1_DAY',
  EVENT_REMINDER_1_HOUR: 'EVENT_REMINDER_1_HOUR',
  APPLICATION_APPROVED: 'APPLICATION_APPROVED',
  APPLICATION_REJECTED: 'APPLICATION_REJECTED'
};
